name: Run Scheduled Match Update

on:
  schedule:
    - cron: '0 5 * * *'  # 5h UTC = 2h Brasília
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Call FastAPI scheduled job
        run: |
          curl -X POST https://bolao-brasileirao-oy40.onrender.com/matches/matches-update \
            -H "Authorization: Bearer ${{ secrets.MATCH_UPDATE_TOKEN }}"
  run-job-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r ./backend/requirements.txt 
      - name: Install Firefox and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox libdbus-glib-1-2 libgtk-3-0 libx11-xcb1 libxt6 libasound2t64

      - name: Install geckodriver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz
          tar -xzf geckodriver-v0.36.0-linux64.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/
      - name: Check Firefox version and location
        run: |
          which firefox
          firefox --version
      - name: Check geckodriver version and location
        run: |
          which geckodriver
          geckodriver --version
      - name: Verify geckodriver permissions
        run: ls -l /usr/local/bin/geckodriver
      - name: Verify firefox
        run: ls -l /snap/firefox/current/usr/lib/firefox/firefox
      - name: Run test of pytest
        env:
         DATABASE_USER: test
         DATABASE_PASSWORD: test
         DATABASE_HOST: localhost
         DATABASE_PORT: 3306
         DATABASE_NAME: test
         SSL_CA_PATH: /dev/null
         SECRET_KEY: "supersecretfortests"
        run: PYTHONPATH=./backend pytest -s
      