name: Run Scheduled Match Update

on:
  schedule:
    - cron: '0 5 * * *'  # 5h UTC = 2h Brasília
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Call FastAPI scheduled job
        run: |
          curl -X POST https://bolao-brasileirao-oy40.onrender.com/matches/matches-update \
            -H "Authorization: Bearer ${{ secrets.MATCH_UPDATE_TOKEN }}"
  run-job-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run test of pytest
        run: PYTHONPATH=./backend pytest -s
      