name: Run Scheduled Match Update

on:
  schedule:
    - cron: '0 5 * * *'  # 5h UTC = 2h Brasília
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Call FastAPI scheduled job
        run: |
          curl -X POST https://bolao-brasileirao-oy40.onrender.com/matches/matches-update \
            -H "Authorization: Bearer ${{ secrets.MATCH_UPDATE_TOKEN }}"
  run-job-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r ./backend/requirements.txt      
      - name: Run test of pytest
        run: PYTHONPATH=./backend pytest -s
      